insert into RAW_VULSCAN_DATA
(IP,
DNS,
NETBIOS,
TRACKING_METHOD,
OS,
IP_STATUS,
QID,
TITLE,
VULN_STATUS,
TYPE,
SEVERTIY,
FIRST_DETECTED,
LAST_DETECTED,
TIMES_DETECTED,
DATE_LAST_DETECTED,
CVEID,
VENDOR_REF,
BUGTRAQID,
THREAT,
IMPACT,
SOLUTION,
EXPLOITABILITY,
ASSOCIATED_MALWARE,
RESULTS,
PCI_VULN,
CATEGORY) 
VALUES (
'172.27.7.30', 
'', 
'', 
'IP', 
'Red Hat Enterprise Linux Server 5.11', 
'host scanned found vuln', 
87387, 
'Oracle WebLogic Server Remote Code Execution Vulnerability (Oracle Security Alert Advisory - CVE-2019-2729)', 
'Active', 
'Vuln', 
5, 
'9/15/19', 
'2/2/20', 
21, 
'', 
'CVE-2019-2729', 
'Oracle Security Alert Advisory - CVE-2019-2729', '', 
'This Security Alert Bypasses CVE-2019-2725 Patch, a deserialization vulnerability in Oracle WebLogic Server. This remote code execution vulnerability is remotely exploitable without authentication.\n\nAffected Versions:\nOracle WebLogic Server Version 10.3.6.0.0\nOracle WebLogic Server Version 12.1.3.0.0\nOracle WebLogic Server Version 12.2.1.3.0\n\nQID Detection Logic (Unauthenticated):\nType: Confirmed\nThe qid sends a HTTP POST payload to urls:_async/AsyncResponseService, _async/AsyncResponseServiceHttps, _async/AsyncResponseServiceJms, _async/AsyncResponseServiceSoap12, _async/AsyncResponseServiceSoap12Https, async/AsyncResponseServiceSoap12Jms, vulnerable hosts will execute the payload\n\nQID Detection Logic (Unauthenticated):\nType: Potential\nThe qid check the version via the classpath servlet, then check if the following urls are accessible:_async/AsyncResponseService, _async/AsyncResponseServiceHttps, _async/AsyncResponseServiceJms, _async/AsyncResponseServiceSoap12, _async/AsyncResponseServiceSoap12Https, async/AsyncResponseServiceSoap12Jms, vulnerable hosts will execute the payload\n\n\nQID Detection Logic (Authenticated):\nOperating System: Linux\nThis QID checks to see if Oracle WebLogic Server process is listening on any of the TCP ports. If so, for version 12.x it gets the "Oracle_Home" path, navigates to that directory and reads "registry.xml" to verify vulnerable version of weblogic is running or not. . The QID then checks if the corresponding patch is applied or not under Oracle_Home/inventory/patches/.\nFor version 10.3.6.x, it gets the "Oracle_Home" path, navigates to that directory and reads "registry.xml" and the file "Oracle_Home"/patch_wls1036/registry/patch-registry.xmlt to check if the installed version is patched.\n\nQID Detection Logic (Authenticated):\nOperating System: Windows\nFor affected 12.x version\nThe QID checks the "Oracle_Home" path with help of the registry key "HKLM\\Software\\Oracle". The QID verifies if the affected WebLogic version is installed. . . The QID then checks if the corresponding patch is applied or not under Oracle_Home\\inventory\\patches\\.\n\nFor 10.3.6.0\nThe QID checks if WebLogic v10.3.6.0 is installed by looking at the file <INSTALL DRIVE>\\Oracle\\Middleware\\wlserver_10.3\\.product.properties. The QID then checks if the corresponding patch is applied or not.', 
'A remote attacker could exploit this vulnerability to execute arbitrary code on the targeted system.', 
'The vendor has released patches for these issues. Customers are advised to refer to Oracle Security Alert Advisory - CVE-2019-2729 (https://www.oracle.com/technetwork/security-advisory/alert-cve-2019-2729-5570780.html) for detailed information.\n Patch:\nFollowing are links for downloading patches to fix the vulnerabilities:\n  Oracle Security Alert Advisory - CVE-2019-2729 (https://www.oracle.com/technetwork/security-advisory/alert-cve-2019-2729-5570780.html)', 
'Source: The Exploit-DB\r\nReference:CVE-2019-2729\r\nDescription:Oracle Weblogic 10.3.6.0.0 - Remote Command Execution - The Exploit-DB Ref : 47895\r\nLink:http://www.exploit-db.com/exploits/47895\r\n\r\nSource: Qualys\r\nReference:CVE-2019-2729\r\nDescription:Oracle WebLogic Deserialization RCE Vulnerability (0day) Alert Again (CVE-2019-2725 patch bypassed\r\nLink:https://medium.com/@knownsec404team/knownsec-404-team-alert-again-cve-2019-2725-patch-bypassed-32a6a7b7ca15', 
'', 
'<component name="WebLogic Server" version="10.3.6.0" InstallDir="/oraclesw/oracle/oms12cr5/wlserver_10.3">\n<id>SRUM</id>\n<id>WE1X</id>\n<id>NIP1</id>\n<id>6D9T</id>#', 'yes', 'Web server')